<div id="footer">
    	<div class="inner-footer">
        	<p><strong>Copyright by Bút chì màu. All right reserved.</strong><br><strong>Địa chỉ:</strong> 15 - Đường 38 - Khu phố 8 - Phường Hiệp Bình Chánh - Quận Thủ Đức - TP HCM<br><strong>Điện Thoại:</strong> 083 7267231 - <strong>Email:</strong> <a href="mailto:info@butchitmau.vn">info@butchitmau.vn</a> - <strong>Website:</strong> <a href="#">www.butchimau.vn</a></p>        </div><!--end inner-->
    </div><!--footer--->
