<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<title>Trang Chủ</title>
		<link rel="stylesheet" type="text/css" href="css/style.css" />
		<link href="css/jqtransform.css" rel="stylesheet">
		<script src="js/jquery.min.js" type="text/javascript"></script>
			<script type="text/javascript" src="js/jquery.jqtransform.js" ></script>
			<script language="javascript">
				$(function(){
					$('.transform').jqTransform();
				});
			</script>
		<script type="text/javascript">
			
			$(document).ready(function(){
				$('.menu li').click(function(){//over
					$('li.active').removeClass('active');
					$(this).addClass('active');
				})
			})
		</script>
</head>
   
